In [1]:
import os

# Define the folders we need
folders = [
    "data/raw",
    "data/processed",
    "notebooks",
    "sql",
    "dashboard",
    "reports"
]

# Create each folder if it doesn't already exist
for folder in folders:
    os.makedirs(folder, exist_ok=True)
    print(f"Created folder: {folder}")

Created folder: data/raw
Created folder: data/processed
Created folder: notebooks
Created folder: sql
Created folder: dashboard
Created folder: reports

In [2]:
%%writefile requirements.txt
pandas
numpy
matplotlib
seaborn
plotly
sqlalchemy
requests
scipy
jupyter

Writing requirements.txt

In [3]:
import os
import pandas as pd

In [ ]:
#files_to_load = [
 #   "01_fund_master.csv",
  #  "02_nav_history.csv",
 #   "03_aum_by_fund_house.csv",
 #   "04_monthly_sip_inflows.csv",
  #  "05_category_inflows.csv",
  #  "06_industry_folio_count.csv",
 #   "07_scheme_performance.csv",
  #  "08_investor_transactions.csv",
 #   "09_portfolio_holdings.csv",
 #   "10_benchmark_indices.csv"

In [5]:
import os
os.getcwd()

'C:\\Mutual_Fund_Capstone_Project'

In [4]:
df_fund_master = pd.read_csv("data/raw/01_fund_master.csv")
df_nav_history = pd.read_csv("data/raw/02_nav_history.csv")
df_aum_by_fund_house = pd.read_csv("data/raw/03_aum_by_fund_house.csv")
df_monthly_sip_inflows = pd.read_csv("data/raw/04_monthly_sip_inflows.csv")
df_category_inflows = pd.read_csv("data/raw/05_category_inflows.csv")
df_industry_folio_count = pd.read_csv("data/raw/06_industry_folio_count.csv")
df_scheme_performance = pd.read_csv("data/raw/07_scheme_performance.csv")
df_investor_transactions = pd.read_csv("data/raw/08_investor_transactions.csv")
df_portfolio_holdings = pd.read_csv("data/raw/09_portfolio_holdings.csv")
df_benchmark_indices = pd.read_csv("data/raw/10_benchmark_indices.csv")

In [9]:
df_fund_master.head()

,amfi_code,fund_house,scheme_name,category,sub_category,plan,launch_date,benchmark,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount,fund_manager,risk_category,sebi_category_code
0,119551,SBI Mutual Fund,SBI Bluechip Fund - Regular Plan - Growth,Equity,Large Cap,Regular,2006-02-14,NIFTY 100 TRI,1.54,1.0,500,1000,Sohini Andani,Moderate,EC01
1,119552,SBI Mutual Fund,SBI Bluechip Fund - Direct Plan - Growth,Equity,Large Cap,Direct,2013-01-01,NIFTY 100 TRI,0.66,1.0,500,1000,Sohini Andani,Moderate,EC01
2,119598,SBI Mutual Fund,SBI Small Cap Fund - Regular Plan - Growth,Equity,Small Cap,Regular,2009-09-09,BSE 250 SmallCap TRI,1.43,1.0,500,1000,R. Srinivasan,Very High,EC03
3,119599,SBI Mutual Fund,SBI Small Cap Fund - Direct Plan - Growth,Equity,Small Cap,Direct,2013-01-01,BSE 250 SmallCap TRI,0.72,1.0,500,1000,R. Srinivasan,Very High,EC03
4,119120,SBI Mutual Fund,SBI Magnum Gilt Fund - Regular Plan - Growth,Debt,Gilt,Regular,2000-12-30,CRISIL Dynamic Gilt Index,0.77,0.0,500,1000,Dinesh Ahuja,Low,DC02

In [10]:
df_fund_master.shape

(40, 15)

In [11]:
df_fund_master.dtypes

amfi_code               int64
fund_house             object
scheme_name            object
category               object
sub_category           object
plan                   object
launch_date            object
benchmark              object
expense_ratio_pct     float64
exit_load_pct         float64
min_sip_amount          int64
min_lumpsum_amount      int64
fund_manager           object
risk_category          object
sebi_category_code     object
dtype: object

In [12]:
df_nav_history.head()

   amfi_code        date      nav
0     119551  2022-01-03  54.3856
1     119551  2022-01-04  54.3474
2     119551  2022-01-05  54.6869
3     119551  2022-01-06  55.4550
4     119551  2022-01-07  55.3692

In [14]:
df_nav_history.shape

(46000, 3)

In [15]:
df_nav_history.dtypes

amfi_code      int64
date          object
nav          float64
dtype: object

In [16]:
df_aum_by_fund_house.head()

         date           fund_house  aum_lakh_crore  aum_crore  num_schemes
0  2022-03-31      SBI Mutual Fund            6.05     605000          186
1  2022-03-31  ICICI Prudential MF            4.65     465000          216
2  2022-03-31     HDFC Mutual Fund            4.35     435000          195
3  2022-03-31      Nippon India MF            2.70     270000          177
4  2022-03-31    Kotak Mahindra MF            2.70     270000          168

In [17]:
df_aum_by_fund_house.shape

(90, 5)

In [18]:
df_aum_by_fund_house.dtypes

date               object
fund_house         object
aum_lakh_crore    float64
aum_crore           int64
num_schemes         int64
dtype: object

In [19]:
df_monthly_sip_inflows.head()

,month,sip_inflow_crore,active_sip_accounts_crore,new_sip_accounts_lakh,sip_aum_lakh_crore,yoy_growth_pct
0,2022-01,11517,4.91,9.10,4.80,NaN
1,2022-02,11438,4.93,8.20,4.85,NaN
2,2022-03,12328,5.09,10.50,5.01,NaN
3,2022-04,11863,5.48,9.52,5.12,NaN
4,2022-05,12286,5.55,8.10,5.15,NaN

In [20]:
df_monthly_sip_inflows.shape

(48, 6)

In [21]:
df_monthly_sip_inflows.dtypes

month                         object
sip_inflow_crore               int64
active_sip_accounts_crore    float64
new_sip_accounts_lakh        float64
sip_aum_lakh_crore           float64
yoy_growth_pct               float64
dtype: object

In [22]:
df_category_inflows.head()

     month         category  net_inflow_crore
0  2024-04        Large Cap            2413.0
1  2024-04          Mid Cap            3897.0
2  2024-04        Small Cap            3533.0
3  2024-04        Flexi Cap            4947.0
4  2024-04  Large & Mid Cap            4214.0

In [23]:
df_category_inflows.shape

(144, 3)

In [24]:
df_category_inflows.dtypes

month                object
category             object
net_inflow_crore    float64
dtype: object

In [25]:
df_industry_folio_count.head()

,month,total_folios_crore,equity_folios_crore,debt_folios_crore,hybrid_folios_crore,others_folios_crore
0,2022-01,13.26,9.28,1.86,0.80,1.33
1,2022-04,13.91,9.74,1.95,0.83,1.39
2,2022-07,13.85,9.69,1.94,0.83,1.38
3,2022-10,14.12,9.88,1.98,0.85,1.41
4,2023-01,14.81,10.37,2.07,0.89,1.48

In [26]:
df_industry_folio_count.shape

(21, 6)

In [27]:
df_industry_folio_count.dtypes

month                   object
total_folios_crore     float64
equity_folios_crore    float64
debt_folios_crore      float64
hybrid_folios_crore    float64
others_folios_crore    float64
dtype: object

In [28]:
df_scheme_performance.head()

,amfi_code,scheme_name,fund_house,category,plan,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade
0,119551,SBI Bluechip Fund - Regular Plan - Growth,SBI Mutual Fund,Large Cap,Regular,12.42,12.36,14.45,11.49,0.87,0.89,0.88,1.29,14.0,-21.70,14288,1.54,4,Moderate
1,119552,SBI Bluechip Fund - Direct Plan - Growth,SBI Mutual Fund,Large Cap,Direct,15.25,11.30,14.23,9.52,1.78,0.87,0.81,1.29,14.0,-24.43,1231,0.66,3,Moderate
2,119598,SBI Small Cap Fund - Regular Plan - Growth,SBI Mutual Fund,Small Cap,Regular,24.56,23.39,20.67,22.16,1.23,0.89,0.94,1.35,25.0,-13.35,19259,1.43,5,Very High
3,119599,SBI Small Cap Fund - Direct Plan - Growth,SBI Mutual Fund,Small Cap,Direct,20.59,23.14,21.82,22.01,1.13,1.04,0.93,1.67,25.0,-24.78,36061,0.72,4,Very High
4,119120,SBI Magnum Gilt Fund - Regular Plan - Growth,SBI Mutual Fund,Gilt,Regular,5.34,6.07,5.43,4.47,1.60,0.22,1.52,2.11,4.0,-2.30,24101,0.77,5,Low

In [29]:
df_scheme_performance.shape

(40, 19)

In [30]:
df_scheme_performance.dtypes

amfi_code               int64
scheme_name            object
fund_house             object
category               object
plan                   object
return_1yr_pct        float64
return_3yr_pct        float64
return_5yr_pct        float64
benchmark_3yr_pct     float64
alpha                 float64
beta                  float64
sharpe_ratio          float64
sortino_ratio         float64
std_dev_ann_pct       float64
max_drawdown_pct      float64
aum_crore               int64
expense_ratio_pct     float64
morningstar_rating      int64
risk_grade             object
dtype: object

In [31]:
df_investor_transactions.head()

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,2024-01-01,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,2024-01-01,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending

In [32]:
df_investor_transactions.shape

(32778, 13)

In [33]:
df_investor_transactions.dtypes

investor_id            object
transaction_date       object
amfi_code               int64
transaction_type       object
amount_inr              int64
state                  object
city                   object
city_tier              object
age_group              object
gender                 object
annual_income_lakh    float64
payment_mode           object
kyc_status             object
dtype: object

In [34]:
df_portfolio_holdings.head()

,amfi_code,stock_symbol,stock_name,sector,weight_pct,market_value_cr,current_price_inr,portfolio_date
0,119551,POWERGRID,Power Grid Corporation,Utilities,13.85,737.09,6011.08,2025-12-31
1,119551,HDFCBANK,HDFC Bank Ltd,Banking,11.19,88.97,1074.65,2025-12-31
2,119551,GRASIM,Grasim Industries Ltd,Diversified,9.90,208.45,5964.59,2025-12-31
3,119551,DRREDDY,Dr. Reddy's Laboratories,Pharma,4.76,161.32,3748.82,2025-12-31
4,119551,ASIANPAINT,Asian Paints Ltd,Paints,10.25,725.90,1321.45,2025-12-31

In [35]:
df_portfolio_holdings.shape

(322, 8)

In [36]:
df_portfolio_holdings.dtypes

amfi_code              int64
stock_symbol          object
stock_name            object
sector                object
weight_pct           float64
market_value_cr      float64
current_price_inr    float64
portfolio_date        object
dtype: object

In [37]:
df_benchmark_indices.head()

         date index_name  close_value
0  2022-01-03    NIFTY50     17492.79
1  2022-01-04    NIFTY50     17689.64
2  2022-01-05    NIFTY50     17835.05
3  2022-01-06    NIFTY50     17878.51
4  2022-01-07    NIFTY50     17759.15

In [38]:
df_benchmark_indices.shape

(8050, 3)

In [39]:
df_benchmark_indices.dtypes

date            object
index_name      object
close_value    float64
dtype: object

In [5]:
#Understand fund master: print unique,fund houses, categories,sub-categories, risk grades
df_fund_master.fund_house.unique()

array(['SBI Mutual Fund', 'HDFC Mutual Fund', 'ICICI Prudential MF',
       'Nippon India MF', 'Kotak Mahindra MF', 'Axis Mutual Fund',
       'Aditya Birla Sun Life MF', 'UTI Mutual Fund', 'Mirae Asset MF',
       'DSP Mutual Fund'], dtype=object)

In [7]:
df_fund_master.category.unique()

array(['Equity', 'Debt'], dtype=object)

In [6]:
df_fund_master.sub_category.unique()

array(['Large Cap', 'Small Cap', 'Gilt', 'Mid Cap', 'Short Duration',
       'Value', 'Liquid', 'Index/ETF', 'Flexi Cap', 'Index',
       'Large & Mid Cap', 'ELSS'], dtype=object)

In [9]:
df_fund_master.risk_category.unique()

array(['Moderate', 'Very High', 'Low', 'High', 'Moderately High'],
      dtype=object)

In [ ]:
missing_codes = df_master[~df_master['scheme_code'].isin(nav_codes)]['scheme_code'].unique()

In [10]:
master_codes = df_fund_master['amfi_code'].unique()
nav_codes = df_nav_history['amfi_code'].unique()

In [12]:
master_codes

array([119551, 119552, 119598, 119599, 119120, 100016, 125497, 100033,
       125498, 100025, 120503, 120504, 120505, 120506, 120507, 118632,
       118633, 118634, 118635, 118636, 120841, 120842, 120843, 120844,
       119092, 119093, 119094, 119095, 101206, 101207, 101208, 102885,
       102886, 102887, 148567, 148568, 148569, 149322, 149323, 149324])

In [14]:
missing_codes = df_fund_master[~df_fund_master['amfi_code'].isin(nav_codes)]['amfi_code'].unique()

In [15]:
missing_codes

array([], dtype=int64)

Findings:  Total missing codes identified: 0 (array([], dtype=int64))

100% of the schemes listed in the master file map perfectly to the historical price records.